java_library(
    name = "diff",
    srcs = ["IntraLineDiffArgs.java"],
    javacopts = ["-Xdiags:verbose"],
    visibility = ["//visibility:public"],
    deps = [
        "//java/com/google/gerrit/reviewdb:server",
        "//third_party:auto-value",
    ],
)
