java_library(
    name = "client",
    srcs = [
        "client/Column.java",
        "client/Key.java",
        "client/KeyUtil.java",
        "client/StringKey.java",
    ],
    visibility = ["//visibility:public"],
)
